@startuml
rectangle Get Price{
start
:Get User Input;
if (Input = /GetPrice) then (Yes)
  repeat:Select Coin;
  repeat while(Do you need Comparison Coins?) is (Yes) not (No)
 
  repeat:Select Time Period;
  backward :Show Error;
  repeat while(Is it a valid time period?) is (No) not (Yes)

  :Show Price;
else (No)
  if (Is Input a Valid Command) then (Yes)
   :Do Another Activity;
  else (No)
  :Show Error;
  endif
endif
stop
@enduml
