name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 matplotlib pybuilder python-telegram-bot requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: lint
        run: |
          autopep8 --in-place --recursive ./src/
      - name: Test and Build
        run: |
          pyb --verbose
